num = int(input('Digite o numero ! '))
print('A tabuada do numero {} é !\n'.format(num))
print('1x{}='.format(num), num*1)
print('2x{}='.format(num), num*2)
print('3x{}='.format(num), num*3)
print('4x{}='.format(num), num*4)
print('5x{}='.format(num), num*5)
print('6x{}='.format(num), num*6)
print('7x{}='.format(num), num*7)
print('8x{}='.format(num), num*8)
print('9x{}='.format(num), num*9)
print('10x{}='.format(num), num*10)
